### ISSUE TITLE
Keyword to determine if a window is open

### ISSUE THREAD

**Issue by nathanwonnacott** [robotframework/SwingLibrary#100]
I think that this library would benefit from a keyword used to determine if a window is open. Note that I'm not asking for a keyword that causes a failure if a window doesn't exist, but rather one that returns a Boolean so that it can be used in an if statement.

An alternative would be a keyword that returns a list of all open windows so that they can be checked manually.

**Comment by badari412** [comment]
@nathanwonnacott I think we already have a keyword to get a list of all the open windows. Go thru this link:[ List Windows](http://robotframework.org/SwingLibrary/SwingLibrary-1.9.7.html#List%20Windows). Using this you can write your own keyword which returns a boolean value.

**Comment by nathanwonnacott** [comment]
@badari412 You're right. I think it would still be sort of nice as a built in keyword, but since there is a reasonable workaround, I'll go ahead and close the issue.
