### ISSUE TITLE
Enhancement Request : Find a label using it's text

### ISSUE THREAD

**Issue by badari412** [robotframework/SwingLibrary#102]
Currently (swinglibrary 1.9.7), finding a label is possible using only it's index or name. But usually SwingUI developers tend to forget or not give any names to the most of the components for e.g. buttons, labels etc. So wouldn't be nice to add an ability to look for a label using it's text similar to the way we find buttons? This will help with the keywords Label Should Exist, Label Should Not Exist etc. Using text is more reliable than using index.

Changing LabelOperatorFactory.java from 
`    public LabelOperator createOperatorByName(String name) {
        return new LabelOperator((ContainerOperator) Context.getContext(), new ByNameComponentChooser(name));
    }
}`

to

`    public LabelOperator createOperatorByName(String name) {
        return new LabelOperator((ContainerOperator) Context.getContext(), new ByNameOrTextComponentChooser(name));
    }
}`

will do the trick.  If my request makes any sense to you people, let me know I will work on it.

**Comment by mihaiparvu** [comment]
Sounds like a very good enhancement and I don't see any problems that could arise by this change.
Are you still interested, @badari412 in providing a pull-request?

**Comment by badari412** [comment]
Thanks for responding @mihaiparvu . Will submit the pull request in a day or so.
