### ISSUE TITLE
Add java.awt.Container to default Context Verifier?

### ISSUE THREAD

**Issue by nathanwonnacott** [robotframework/SwingLibrary#104]
Is there a reason why Container is not a valid context for many keywords?

I believe that in order to allow it, all you would need to do is add it to the array returned by DefaultContextVerifier.getExpectedClasses().

I would just add it myself and create a pull request except that I suspect that there is some reason why it wasn't that way in the first place and I have no idea what it is.

**Comment by mihaiparvu** [comment]
Just adding the `Container.class` to the array returned by `DefaultContextVerifier.getExpectedClasses()` won't work. All the existing members of the array are subclasses of the Container object. Those subclasses also have an accessible context that is used by Jemmy to identify them. The Container superclass does not. It is a generic object that can contain other AWT components.

I could be missing something however, but if you can find a way to make it work feel free to submit a pull request.

**Comment by mihaiparvu** [comment]
Closing for now. Can be reopened if needed.
