### ISSUE TITLE
Cannot handle Components JXPanel 

### ISSUE THREAD

**Issue by abhinavnandkar** [robotframework/SwingLibrary#106]
Hi,

I'm working with a java swing application which has components like JXPanel 
And i'm unable to click on this component using swing library keywords.
 

example
Level: 13 Component: com.amdocs.uif.widgets.PanelNative$JXPanel Index: 356 Name: xFlashes

So this is a tabbed panel which needs to be clicked.
No keywords is able to click on this JXPanel

**Comment by mihaiparvu** [comment]
JXPanel is not a native Swing component, therefore there is no keyword to control it. SwingLibrary only supports objects that extend JComponent or its subclasses.
