### ISSUE TITLE
License issue (GPL software cannot be included in Apache projects)

### ISSUE THREAD

**Issue by abego** [robotframework/SwingLibrary#127]
SwingLibrary is released under an Apache license. However SwingLibrary is using Jemmy, a software provided under a GPLv2 licence.

The Apache license is compatible with the GPL software in one direction: GPLv3 software may use Apache license. "However, GPLv3 software cannot be included in Apache projects. The licenses are incompatible in one direction only, and it is a result of ASF's licensing philosophy and the GPLv3 authors' interpretation of copyright law." (https://apache.org/licenses/GPL-compatibility.html) (Also holds for GPLv2)

To avoid legal issues it seems to be necessary to change the SwingLibrary's license to GPL or to avoid using Jemmy (and any other GPL licensed software).

**Comment by pekkaklarck** [comment]
AFAIK Jemmy is license under GPL with classpath exception and it explicitly allows this kind of usage. Do you have proofs otherwise?

**Comment by abego** [comment]
You are right. I was not aware of the classpath exception.
