### ISSUE TITLE
Possibility to work with Combo Box when it is a table cell

### ISSUE THREAD

**Issue by karusha** [robotframework/SwingLibrary#128]
Dear SwingLibrary gurus,

Would it be possible to add "Select From Table Cell Combo Box" keyword similar to "Select From Combo Box" where Table cell is defined as Table identifier, row, column.

Many thanks in advance.

**Comment by rticau** [comment]
@karusha  Sorry for such a late reply. Unfortunately we couldn't find the time to adress this issue and it seems that it is not a simple (if even possible) enhacement. Did you managed to find an workaround by now?

**Comment by karusha** [comment]
@rticau thank you for your message, no I did not manage to find an workarounds, but probably it is not very critical in our case, keep me posted, if there are any changes from your end.

**Comment by URunDEAD** [comment]
Hello @karusha! This feature is already implemented. The keyword for this particular case is [Set Table Cell Value](https://robotframework.org/SwingLibrary/SwingLibrary.html#Set%20Table%20Cell%20Value).
For example, setting the Combobox from a table at position 1, 0 to "example":
```
Set Table Cell Value
    setTableCellValue  ${tableName}  1  0  example
```

Please let me know if I did not understand your question correctly

**Comment by rticau** [comment]
no updates, closing.
