### ISSUE TITLE
Is it possible to use SwingLibrary without RobotFramework?

### ISSUE THREAD

**Issue by ssanmaru** [robotframework/SwingLibrary#145]
Hello there,
Is it possible to use this SwingLibrary project to automate any Swing based apps without using Robot framework?

Please advise

Thanks,
San

**Comment by rticau** [comment]
SwingLibrary can be used only together with RobotFramework. What is exactly that you want to accomplish?

**Comment by ssanmaru** [comment]
I want to use SwingLibrary as a standalone automated tool to write automated test scripts for Swing based apps. SwingLibrary is a great tool but was wondering, if it is possible to decouple the Robot framework and use it as a standalone tool. 

Also, I tried with Jemmy-v2, was not clear how to include the depedent jars while starting up the application. I have posted a question on Stackoverflow [here](https://stackoverflow.com/questions/66059839/how-to-include-depedent-jar-files-while-launching-a-swing-demo-app-swingset3de) but no luck so far.
Thanks,
San

**Comment by mihaiparvu** [comment]
SwingLibrary also uses Jemmy internally to automate Java Swing applications, but is a test library written specifically for Robot Framework and it won't work independently of it.  If you don't want to use Jython for your acceptance tests you can give [remoteswinglibrary ](https://github.com/robotframework/remoteswinglibrary) a try. It provides a wrapper on top of SwingLibrary that will work with Python, but you still need to to have Robot Framework installed.

Try to post your SwingLibrary related questions in the [Slack channel](https://robotframework-slack-invite.herokuapp.com/) dedicated to SwingLibrary or [forum section](https://forum.robotframework.org/c/libraries/swinglibrary/).
I will close the issue as it is neither bug or feature request in the library itself.
