### ISSUE TITLE
Class Not Found Error when upgrade to jdk to version 1.8.0_301: Java class. sun/awt/SunToolkit$InfiniteLoop

### ISSUE THREAD

**Issue by Bellama1** [robotframework/SwingLibrary#148]
After upgrade to java 8u301, a error occurs when call keyword "Set Jemmy Timeouts". The error message is :java.lang.ClassNotFoundException: sun.awt.SunToolkit$InfiniteLoop. Please kindly  help check this issue
![image](https://user-images.githubusercontent.com/39483613/126950785-d1a5be1d-c8a2-4b90-8021-74e0543de734.png)

**Comment by mihaiparvu** [comment]
Fixed in 25ded76b20af2cc36f74fce7780ac6e7d9717668.
