### ISSUE TITLE
java.lang.ClassNotFoundException: sun.awt.SunToolkit$InfiniteLoop from RemoteSwingLibrary.List Windows

### ISSUE THREAD

**Issue by mvuorenmaa** [robotframework/SwingLibrary#149]
After upgrading to Java 11.0.12 the application launches in our test set started to fail. After investigating and upgrade to remoteswinglibrary version 2.2.9 the application launch seems to work better, but we started getting a new error concerning **RemoteSwingLibrary.List Windows**. The keyword fails with message: **java.lang.ClassNotFoundException: sun.awt.SunToolkit$InfiniteLoop**

I'm guessing this concerns more SwingLibrary than RemoteSwingLibrary.

EDIT: Also **Select Main Window** is producing the same error. Our tests are working fine with the previous Java version 11.0.11.

**Comment by mihaiparvu** [comment]
Fixed in [RemoteSwingLibrary 2.3.0](https://github.com/robotframework/remoteswinglibrary/releases/tag/2.3.0).

**Comment by mvuorenmaa** [comment]
Indeed, verified. This helps a lot. Thank you.
