### ISSUE TITLE
problem with Click On Table Cell

### ISSUE THREAD

**Issue by pmakowski** [robotframework/SwingLibrary#15]
Hello,

from time to time, I have problem with Click On Table Cell
I get a "Scrolling" and it doesn't click on the table cell 
is there another way to select a row or a cell in a table ?

I'm using 
Click On Table Cell    materialTable    ${row}    0    1    LEFT BUTTON

**Comment by sriharshahonne** [comment]
Hello,

I am still having a problem with Click On Table Cell as this keyword doesn't click on the table cell.

I am passing the correct row (verified) for selection but not sure what else I am missing.

Below is my code:
${row} =    Find Table Row With Subtext    ${TABLE_NAME}    ${elementName}    ${EMPTY}

Click On Table Cell    ${TABLE_NAME}    ${row}    
 ...${TABLE_COLUMN_ID}    ${SINGLE_CLICK_COUNT}

Can anyone help me with this?
