### ISSUE TITLE
Timeout exception occurs with high frequency after using keyword "Send Keyboard Event VK_TAB"

### ISSUE THREAD

**Issue by Bellama1** [robotframework/SwingLibrary#150]
Hi ,
   I'm using swinglibrary with version 2.2.2 , java version jdk1.8_301 to test java GUI application. I found keywords related with combox and textfield would fail with timeout exception with a bit high frequency after calling keyword "**Send Keyboard Event VK_TAB**", the fail rate is about **50**%. 
For example:
	Insert Into Text Field    identifier    text
        Send Keyboard Event    VK_TAB
	Select From Combo Box    identifier    comboItemIdentifier
I repeat these keywords ten times, five will fails with "org.netbeans.jemmy.TimeoutExpiredException: Wait popup expanded
". Same situation will happens when calling "Insert Into Text Field, Clear Text, Check Combobox Count..."
 Do you have any idea what could I do to  avoid this unstable situation or anything could be optimized in swinglibrary?

**Comment by Bellama1** [comment]
Please hava a look at this issue, thanks in advance

**Comment by Bellama1** [comment]
Hi there, is there any update about this issue?

**Comment by mihaiparvu** [comment]
I'll try to have a look at this issue soon.

**Comment by mihaiparvu** [comment]
Using a test application, containing `TextField` and `ComboBox` components I was unable to replicate your problem after running
```robotframework
Send Keyboard Event     VK_TAB
```
Using several runs like you describe I never had any issues. Tested this on both Linux and Windows.
Are there any more details you can provide to help me figure out the issue, like a demo app with an easy to reproduce scenario?

Is there a reason why you need to cycle through components with the `VK_TAB` key? Because all the SwingLibrary keywords need only the identifier to be found, no need for the component to have focus on.

**Comment by Bellama1** [comment]
Unfortunately I can't provide a demo app .  I think this is the scenario: combobox list will be changed on text field value change .  

I did run cases in docker container which image is based on **dorowu/ubuntu-desktop-lxde-vnc:bionic**. Case execution was stable in windows but un-stable in Linux. 

For the application I tested, I have to use "Send keyboard Event" in case like : make APP focus to next component(Like type a order no ,press TAB , all other data will loaded into page) ;  the identifier name is null;  customization component which is not implemented in swinglibrary;

Below is execution report in docker container:
![image](https://user-images.githubusercontent.com/39483613/134286998-c598b6a5-6c76-4817-8c0a-931539158b95.png)
![image](https://user-images.githubusercontent.com/39483613/134287012-0d821715-36ae-49d1-a393-4a5c9ae27345.png)

**Comment by mihaiparvu** [comment]
Can you try using higher values for `Set Jemmy Timeouts`? 
Another workaround would be to use the BuiltIn keyword `Wait Until Keyword Succeeds` to retry the step until it passes.

**Comment by mihaiparvu** [comment]
@Bellama1 any updates on this?

**Comment by Bellama1** [comment]
Thanks for your advice.
 At present,  "Wait Until Keyword Succeeds" is a workaround . I'm still working to looking another solution
 I will close the issue.
