### ISSUE TITLE
Unable to launch Swing application to be tested through Robot Framework in Java

### ISSUE THREAD

**Issue by Zarmeena** [robotframework/SwingLibrary#154]
I am using Robot Framework with Java and need to automate testing of swing applications. Have added the following dependencies and plugin in pom.xml:

	    <dependency>
	    <groupId>org.robotframework</groupId>
	    <artifactId>robotframework</artifactId>
	    <version>4.0.3</version>
	</dependency>
	  
	<dependency>
        <groupId>org.robotframework</groupId>
        <artifactId>swinglibrary</artifactId>
       <version>2.2.2</version>
	</dependency>
  
    <plugin> 
      <groupId>org.robotframework</groupId>
      <artifactId>robotframework-maven-plugin</artifactId>
      <version>1.4.6</version>
        <executions>
          <execution>
              <goals>
                <goal>run</goal>
              </goals>
          </execution>
        </executions>  
    </plugin>

Swing application (SUT) is invoked if I have the application in same project. But does not invoke for external jars added to build path. Attached the Robot Script for reference
[Test_Case_3.txt](https://github.com/robotframework/SwingLibrary/files/7519495/Test_Case_3.txt)

Please let me know how to invoke external swing application for testing

**Comment by mihaiparvu** [comment]
Did you try to add the external jars to `CLASSPATH` system variable?

**Comment by rticau** [comment]
No updates so closing.
