### ISSUE TITLE
Update Abbot dependency

### ISSUE THREAD

**Issue by DanielGaldames** [robotframework/SwingLibrary#41]
To reproduce  write some simple app and close the main window, i.e. swinglib.runKeyword("closeWindow, ["SomeWindowName"]). It produces the error below using java 1.7 and swinglibrary 1.4.1 or 1.6.0 but it works well on java 1.6.
I've found a patch to this problem at https://github.com/Rethought/swinglibrary_package. It seems to work but it would be better if you can fix it on future releases.

the error:
org.robotframework.abbot.tester.Robot.waitForIdle(Robot.java:645):
Timed out waiting for idle event queue after 957 events

**Comment by jussimalinen** [comment]
We managed to replicate the "waiting for idle timeout" problem on our atdd-demo project. Using abbot 1.3 gets rid of the "waiting for idle timeout" messages and speeds up the execution considerably.

This means that the update to later Abbot is back on menu.

**Comment by jussimalinen** [comment]
Well, finally the latest abbot is at maven central! 1.9.5 contains the 1.4.0.

**Comment by jussimalinen** [comment]
584052fe083b40de202b42dc16efd6de18a54d35
