### ISSUE TITLE
Unable to run multiple tests in one execution, where tests kill main window

### ISSUE THREAD

**Issue by justingamble** [robotframework/SwingLibrary#45]
# Software versions:

Robot Framework 2.8.1 (Jython 2.5.3 on java1.6.0_45)
SwingLibray 1.6.0

Operating System: 64-bit Linux (with Mint v14)
$ uname -a
Linux adelais 3.5.0-17-generic #28-Ubuntu SMP Tue Oct 9 19:31:23 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
# What I am trying to test
1. launch my application with command-line parameters
2. review with RobotFramework/SwingLibrary that the initial GUI screen has settings that match the command-line parameters
3. close the application
4. go to step 1 (re-launch the application with the next set of command-line parameters)
# Issue

I found the above to work fine with the demo application found at
https://github.com/robotframework/SwingLibrary/wiki/SwingLibrary-Demo

With my company's application, however, it does not work. After step 3 above, RobotFramework/SwingLibrary aborts execution early and I am not able to run the 2nd, 3rd, 4th, and so on tests.

(I found a workaround: I put the tests for the 2nd, 3rd, 4th.. tests in a separate input file and run RobotFramework against each input file separately.  This works ok, but I need my program to combine the results of all the test runs, and so I am not taking advantage of RobotFramework's nice test summary capabilities).

When I run the tests individually they are fine.  The issue only exists when I run them during the same Robot Framework (RF) execution.  I have tried putting all the RF tests in the same file, or putting them in separate files in a directory.  I have tried exiting the application in different ways (via menu File|Exit, via Close Window keyword, via Run keyword to explicitly kill the running pid).

When run without RobotFramework, my company's application appears to exit gracefully, returning a value of 0 and killing all threads.
# Details

1) When the tests are all in the same file, and "Test Setup" and "Test Teardown" are used to start/stop the application, then Robot Framework dies as soon as it gets to the 2nd test. It prints the name of the 2nd test, and that's it.  The log.html and report.html is not generated. It does, however, generate debug.txt and output.xml
(though the output.xml is not complete; Firefox won't open it; parsing error)

2) When the tests are in different files, and each file has a "Suite Setup" and "Suite Teardown" (or no "Suite Teardown" at all - same result), then RobotFramework dies on the 2nd test with this output:

```
[ ERROR ] Unexpected error: ValueError: I/O operation on closed file            
Traceback (most recent call last):
  None
Verify Dialog                                                         Traceback (most recent call last):
File "/opt/jython/jython2.5.3/bin/jybot", line 6, in <module>
  run_cli(sys.argv[1:])
File "/opt/jython/jython2.5.3/Lib/site-packages/robot/run.py", line 415, in run_cli
  RobotFramework().execute_cli(arguments)
File "/opt/jython/jython2.5.3/Lib/site-packages/robot/utils/application.py", line 44, in execute_cli
  rc = self._execute(arguments, options)
File "/opt/jython/jython2.5.3/Lib/contextlib.py", line 22, in __exit__
  self.gen.next()
File "/opt/jython/jython2.5.3/Lib/contextlib.py", line 22, in __exit__
  self.gen.next()
File "/opt/jython/jython2.5.3/Lib/site-packages/robot/utils/application.py", line 58, in _logging
  self._logger.close()
File "/opt/jython/jython2.5.3/Lib/site-packages/robot/output/logger.py", line 127, in close
  logger.close()
File "/opt/jython/jython2.5.3/Lib/site-packages/robot/output/xmllogger.py", line 44, in close
  self.start_errors()
File "/opt/jython/jython2.5.3/Lib/site-packages/robot/output/xmllogger.py", line 136, in start_errors
  self._writer.start('errors')
File "/opt/jython/jython2.5.3/Lib/site-packages/robot/utils/markupwriters.py", line 41, in start
  if attrs else '<%s>' % name, newline)
File "/opt/jython/jython2.5.3/Lib/site-packages/robot/utils/markupwriters.py", line 74, in _write
  self.output.write(self._encode(text))
ValueError: I/O operation on closed file
```

I can provide the exact Robot Framework input files, and etc, if that would help.

Kind regards,
Justin

**Comment by atilacamurca** [comment]
I had a similar issue, where my application needs to call `System.exit`. So what I did was delayed the `System.exit` call for about 3 seconds.

**Comment by mihaiparvu** [comment]
Closing due to no answer from reporter.
