### ISSUE TITLE
Get Table Cell Property docs example needs update

### ISSUE THREAD

**Issue by mkorpela** [robotframework/SwingLibrary#56]
In the example uses none existing: Get Table Cell Properties

**Comment by WojtekKowaluk** [comment]
I have stumbled upon this when doing https://github.com/robotframework/SwingLibrary/pull/64 and fixed it there.

**Comment by WojtekKowaluk** [comment]
fixed inhttps://github.com/robotframework/SwingLibrary/pull/68
