### ISSUE TITLE
Using Tooltiptext as identifier for identifying TextField

### ISSUE THREAD

**Issue by OatsTester77** [robotframework/SwingLibrary#57]
We are trying to use Swing Library to Automate Swing Based application.In our Application most of the identifiers(i.e. Name,Text etc)are null.So robot framework is unable to identify any object.Only 'tooltiptext' identifier has unique values with which we can identify all the objects. But it seems using the swing library with robot framework only supports 'name' identifier. 

Is there any way we can use other indentifiers instead of 'name' identifier?

**Comment by jussimalinen** [comment]
Not currently, but pull requests are welcome!

**Comment by mgladki** [comment]
I have created pull request with this feature.

**Comment by jussimalinen** [comment]
Thanks! I am now back from my vacation. Once we make a new release, I will include this.
