### ISSUE TITLE
Swing explorer does not anymore exist

### ISSUE THREAD

**Issue by aaltat** [robotframework/SwingLibrary#72]
Ugh

It seems that swing explorer does not anymore exist, at least for me the http://www.swingexplorer.com/ and https://swingexplorer.dev.java.net/ habe beem giving error for a week or so. Should we provide a backup from somewhere and update docs too?

-Tatu

**Comment by jussimalinen** [comment]
Damn. Do you have the backup jars? I think I have them somewhere, but I cant seem to find them now.

There is also the issue of license... We would have to check that we would be allowed to redistribute it.

**Comment by mtbc** [comment]
If it's any use then locally I seem to have a `.eclipse/org.eclipse.platform_3.8_155965261/plugins/org.swingexplorer.eclipseplugin_1.6.0.jar`.

**Comment by aaltat** [comment]
I have local backup and I can share jars for a while, if needed. But a permanent solution would be nice to have too. I did found the pages from cache [1] and license seems to be: GNU LESSER GENERAL PUBLIC LICENSE Version 3, 29 June 2007. But the cache does not contain the jar files. 

[1] http://web.archive.org/web/20130122161933/http://www.swingexplorer.com/?page=license

**Comment by HelioGuilherme66** [comment]
This is the jar I have (no source code inside):
https://slack-files.com/T07PJQ9S7-F092N0MN0-2b7ac6cc10

**Comment by aaltat** [comment]
And here is the link: https://www.dropbox.com/sh/vi51d9zcr7qmlif/AABve_KAxmcyCbVBmEHzXHEAa?dl=0

**Comment by jussimalinen** [comment]
Thanks! Looking inside those jar files from @HelioGuilherme66 and @aaltat, they both seem to be the same version (1.6.0 ) and contain the GPL 3.0 license.txt

I guess we can then make them available somewhere. As the docs are gone from the internet as well, some use instructions would be a good idea.

Where could we host these..? Making a github project just for that, with these files in the downloads of a release would be an option, but feels a bit akward.

**Comment by aaltat** [comment]
Can one add them to SwingLibrary project?

**Comment by jussimalinen** [comment]
Hmm.. into the repository? I dont know where else we could put it in the project. (besides creating a release with only those files)

Normally we try to keep jar files out of the repository to make cloning and other git operations as fast as possible, but as there jar files are under 500kb each, I guess that could be acceptable this time.

**Comment by jussimalinen** [comment]
http://www.apache.org/licenses/GPL-compatibility.html Theoretically we could into trouble with adding GPL3 licensed components into an Apache licensed project. (I guess the question is whether SwingExplorer jars are part of the SwingLibrary simply by having been added to same repository.)

To me making a new repository with just the jars and some usage instructions seems the cleanest and safest way.

**Comment by jussimalinen** [comment]
Actually, my bad. The license is LGPL3. But nonetheless, a new project is better also because we can then easily remove it if the swingexplorer's home page reappears.

**Comment by jussimalinen** [comment]
https://github.com/robotframework/swingexplorer/

**Comment by jussimalinen** [comment]
Okay, that does it guess? I wonder if there is someone we could contact about what happened to SwingExplorer....

**Comment by aaltat** [comment]
I think so too. I do not know who or where to contact, does someone else knows? Perhaps asking on a rf user group too...

**Comment by jussimalinen** [comment]
Google code hides the emails of the developers: https://code.google.com/p/swing-explorer/

Maxim Zakharenkov seems to be main developer https://www.java.net/pub/au/607 (He's name is also in source files.) I just dont see how to contact him anywhere.

**Comment by aaltat** [comment]
There was discussion in slack that Maxim has been reached and he is sorting the issue out.

**Comment by narendranss** [comment]
Any Updates?

**Comment by AndyWu2015** [comment]
waiting for the latest news

**Comment by aaltat** [comment]
I don't have any news. Use the version in https://github.com/robotframework/swingexplorer/

**Comment by robelgado** [comment]
What about the eclipse plugin, anyone here have that?  I don't see the plugin within the git repo

**Comment by AndyWu2015** [comment]
not know much about eclipse plugin, but I did a Intellij IDEA plugin for spy swing elements , see here https://github.com/AndyWu2015/swing-spy

**Comment by apjanke** [comment]
Any update on the Maxim/SwingExplorer story? I'd really like to have an official distribution available again, and especially get access to the source code. If it's a matter of needing some work to set up new hosting for the site/repo, I'd be happy to pitch in if he wants help. Or maybe we could just get an archive of the source code?

**Comment by aaltat** [comment]
I don't have any news, the source code might be here though: https://code.google.com/archive/p/swing-explorer/source/default/source

But I have moved away from the Swing and I am not actively looking on the matter.

**Comment by ArneBab** [comment]
It seems that there’s new activity in https://github.com/swingexplorer/swingexplorer/
