### ISSUE TITLE
Not able to access my swing appn which launched another swing appn using robot swing library

### ISSUE THREAD

**Issue by amitmalpure** [robotframework/SwingLibrary#73]
I have swing application for automation testing. This application launched a client swing application using swing library keyword : 'Start Application In Separate Thread'. But after client application got launched, my swing application becomes unaccessible. How can I solve this?

**Comment by BeniGroza** [comment]
Hi @amitmalpure 

Are you able to use RemoteSwingLibrary? There is a keyword named `Switch To Application ` which may help you.
Br
