### ISSUE TITLE
"Tree Node Should *" keywords should have the jemmy timeout as optional argument

### ISSUE THREAD

**Issue by tarand** [robotframework/SwingLibrary#77]
Looking at all those "Tree Node Should'" keywords: The is only two of them (Tree Node Should Be Leaf and Tree Node Should Not Be Leaf) which explicitly state the need to call "Set jemmy timout" in order to shorten test execution time. I guess that for all the others the same remark is valid. It would also be very helpful, if the kind of time (e.g. JTreeOperator.WaitNodeExpandedTimeout) that must be specified is added.
I would also suggest to add a parameter "timeout=None" in all the arguments. If passed, it should call set jemmy timeout (with the correct type for this call) automatically (and reset it back before returning of course),

This would avoid the following code that I have to add at many places:

${old}= | Set Jemmy Timeout  | ...
Tree Node Should \* ...
Set Jemmy Timeout | ${old}

Note also that this code even is not correct! If the Tree Node Should\* keyword should fail, the timeout is NOT reset, which could cause bad test results for other testcases as a consequence. (Please note how difficult it would be to correct this issue).

**Comment by WojtekKowaluk** [comment]
This sounds like good idea, I will check how hard it would be to implement this.
