### ISSUE TITLE
No Jemmy Output In Logs

### ISSUE THREAD

**Issue by rzezimierz** [robotframework/SwingLibrary#79]
Hello, I've been having a hard time trying to obtain the Jemmy output in Robot log. I'm using SwingLibrary 2.0.3 which claims to have this enabled, but there are no relevant entries in completed suite log. Log Level has been set to DEBUG using proper keyword (Set Log Level DEBUG). When using 2.1.1 with close security windows feature enabled, I see entries starting with *DEBUG xxxx *Jemmy right when it starts to close security windows in Java output, but no trace of these entries after test starts.

**Comment by WojtekKowaluk** [comment]
Hey, good find. I think it is because for security popup closing we create extra instance of Swing Library.
And some data related for logging are stored in static (shared) fields. I will look for best way to fix this.
