### ISSUE TITLE
Robot Framework is not executing in eclipse LUNA

### ISSUE THREAD

**Issue by SumathiChn** [robotframework/SwingLibrary#80]
Hi Team,
  I installed Robot Framework in eclipse ide and created a new maven project.

Mentioned below are the dependencies i used .
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.robotframework</groupId>
  <artifactId>robotframework</artifactId>
  <version>3.0</version>
  <packaging>jar</packaging>

  <name>robot framework</name>
  <url>http://robotframework.org</url>
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>

```
<dependency>
<groupId>com.github.markusbernhardt</groupId>
<artifactId>robotframework-selenium2library-java</artifactId>
<version>1.4.0.8</version>
<scope>test</scope>
```

   </dependency>

   <dependency>
    <groupId>org.bouncycastle</groupId>
    <artifactId>bcpkix-jdk15on</artifactId>
    <version>1.48</version>
   </dependency>

   <dependency>
  <groupId>com.opera</groupId>
  <artifactId>operadriver</artifactId>
  <version>1.5</version>
</dependency>

```
<dependency>
```

  <groupId>org.robotframework</groupId>
  <artifactId>robotframework-maven-plugin</artifactId>
   <version>1.4.6</version>
   <type>maven-plugin</type>
</dependency>

<dependency>
   <groupId>com.sun</groupId>
   <artifactId>tools</artifactId>
   <version>1.6</version>
 </dependency>
  </dependencies>
</project>

I created a txt file and wrote the code in the file
Open Browser  http://www.joecolantonio.com  IE
Close Browser

When i try to run the script using run configurations -> Maven build, execution shows Build SUCCESS. But application is not getting launched. Anybody please provide solution for this issue.

CONSOLE OUTPUT .
[INFO] Scanning for projects...
[INFO] 
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building robot framework 3.0
[INFO] ------------------------------------------------------------------------
[INFO] Downloading: http://apinahwshr5q27:8082/artifactory/libs-release/com/sun/tools/1.6/tools-1.6.pom
[INFO] Downloading: http://apinahwshr5q27:8082/artifactory/libs-snapshot/com/sun/tools/1.6/tools-1.6.pom
[WARNING] The POM for com.sun:tools:jar:1.6 is missing, no dependency information available
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ robotframework ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Robot_Framework\robotframework\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.5.1:compile (default-compile) @ robotframework ---
[INFO] Nothing to compile - all classes are up to date
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.542 s
[INFO] Finished at: 2016-05-24T13:28:42+05:30
[INFO] Final Memory: 10M/24M
[INFO] ------------------------------------------------------------------------

**Comment by WojtekKowaluk** [comment]
Hello, I'm not expert with Eclipse, but can you post screenshot of your run configurations dialog?

**Comment by oanab11** [comment]
Closed due to inactivity.
