### ISSUE TITLE
KW to get checkbox state

### ISSUE THREAD

**Issue by filipecduarte** [robotframework/SwingLibrary#85]
I can't find and kw to get the state from a checkbox,
Only Check Box Should ...

Exist any kw to do this?

**Comment by WojtekKowaluk** [comment]
Only `Check Box Should Be Checked` and  `Check Box Should Be Unchecked` exist and it should be enough for most of use cases.
Why would you need this keyword?

**Comment by filipecduarte** [comment]
Only for get the config status, if is allready in the config that i want, i don't do any thing, if not i check or uncheck.

**Comment by WojtekKowaluk** [comment]
Why not call `Run Keyword And Return Status  Check Box Should Be Checked  ${id}`?

**Comment by filipecduarte** [comment]
Is that i use. I only ask because cold exist and i don't see. Can close the issue. I continue to use that.

On Fri, Jul 22, 2016 at 1:39 PM, Wojtek Kowaluk <notifications@github.com<mailto:notifications@github.com>> wrote:


Why not call Run Keyword And Return Status Check Box Should Be Checked ${id}?

-
