### ISSUE TITLE
Swing keyword taking long time

### ISSUE THREAD

**Issue by viswanathr** [robotframework/SwingLibrary#86]
Swing keyword taking long time to execute.

`KEYWORD: SwingLibrary.Select From Combo Box uploadType, ${operationType}
Start / End / Elapsed:  20160728 14:21:01.133 / 20160728 14:21:57.326 / 00:00:56.193`

The 'Select From Combo Box' keyword took 56 seconds to execute. During this time, we are able to manually select the option from combo box.

Attached robot log and thread dump.
[hanging issue.zip](https://github.com/robotframework/SwingLibrary/files/388535/hanging.issue.zip)

**Comment by mihaiparvu** [comment]
Closing due to no response.
