### ISSUE TITLE
Laughing Panda Maven repository missing

### ISSUE THREAD

**Issue by mtbc** [robotframework/SwingLibrary#87]
https://github.com/robotframework/SwingLibrary/blob/87487ed0dc6a72d45b6f9ed76e7ff64674f34156/pom.xml#L40 has,

``` xml
<url>http://maven.laughingpanda.org/maven2/</url>
```

but,

``` console
$ host maven.laughingpanda.org
Host maven.laughingpanda.org not found: 3(NXDOMAIN)
```

Is there a more reliable repository that would suffice?

**Comment by WojtekKowaluk** [comment]
laughingpanda.org is where one od SwingLibrary dependencied (i.e JDave) is hosted. It is down at the moment (according to google cache it was still working on Aug 10). I don't know any replacement.

**Comment by pekkaklarck** [comment]
Is jDave used in the actual SwingLibrary code or only in tests?

If I remember correctly, jDave is developed by Reaktor. Do you @jussimalinen know about its current status?

**Comment by WojtekKowaluk** [comment]
It is used only in unit tests.

**Comment by jussimalinen** [comment]
Yeah, the JDave is used only on tests. I dont know of any replacement.. I would actually seriously consider at this point getting rid of the unit tests. The acceptance tests written with Robot are quite comprehensive I think?

**Comment by jussimalinen** [comment]
I contacted the maintainers of Laughing Panda and they renewed the domain. Maybe it now starts working.

**Comment by pekkaklarck** [comment]
Great that Laughing Panda is up again. Interesting that nobody else noticed it earlier. If Laughing Panda is not too actively maintained, perhaps jDave developers should be contacted to upload it also to Maven Central. Or is jDave unmaintained too?

If unit test serve no real purpose and it is very unlikely new are needed in the future, getting rid of them is obviously a good idea. If new are needed latter, setting up new unit test infra would be very annoying, though.

**Comment by jussimalinen** [comment]
Last release was Jan 20 2011, version 1.2. So not very active lately...

**Comment by mihaiparvu** [comment]
JDave still not on Maven Central and possibly won't be ever, but Laughing Panda still works and see no reason to remove the unit tests for now. In case there will be problems in the future with the repository we can remove them at that point.
