### ISSUE TITLE
Robot non-functional, falling back to AWT mode

### ISSUE THREAD

**Issue by amolsjain** [robotframework/SwingLibrary#90]
The test swing application seems to work but I get below message in the log, Any idea what it means ?

I am running RIDE 1.5.2.1 running on Python 2.7.12

Robot non-functional, falling back to AWT mode

My test script : 
*** Settings ***
Suite Setup Start Test Application
Library SwingLibrary

*** Test Cases ***
Test Add Todo Item
Start Test Application

*** Keywords ***
Start Test Application
Start Application org.robotframework.swing.testapp.examplesut.TodoListApplication

**Comment by mihaiparvu** [comment]
The error message comes from Abbot, a SwingLibrary dependecy. Robot non-functional refers to the java.awt.Robot class and does not have anything to do with Robot Framework. You can safely igonre this message, it doesn't indicate a problem with your environment.
