### ISSUE TITLE
New Keyword to retrieve items from Tree Node Popup Menu

### ISSUE THREAD

**Issue by muresanrazvan** [robotframework/SwingLibrary#92]
It could be useful to have a keyword to get all items from tree node popup menu. Keywords should work almost the same like Get Menu Items From Popup Menu: Gets item names from the components context tree node popup menu.

**Comment by HelioGuilherme66** [comment]
Please provide a public URL with an example of the "tree node popup menu".

**Comment by muresanrazvan** [comment]
![treenodepopupmenu](https://cloud.githubusercontent.com/assets/23376734/25335565/3ec2fe2e-28fc-11e7-93e7-556fbb630dab.png)
The keyword should return a list with the item names from the popup menu. For example, in the attached snapshot, for tree node 'the java tutorial continued: the rest of the jdk',  the new keyword should return a list of 10 items and for the submenu 'Submenu' should return 2 items
