### ISSUE TITLE
Send Keyboard Event does not work properly

### ISSUE THREAD

**Issue by Babzsak** [robotframework/SwingLibrary#97]
I am using the latest swinglibary with RF for thesting a swing webservice.

I would like to use it like this:
Send Keyboard Event	**VK_UNDERSCORE**

Along the official keyevent documentation (https://docs.oracle.com/javase/7/docs/api/java/awt/event/KeyEvent.html) this would type: _
But instead it fails with the following errormessage:

FAIL : Processing XML-RPC return value failed. Most often this happens when the return value contains characters that are not valid in XML. Original error was: ExpatError: not well-formed (invalid token): line 1, column 180

Either the documentation to this keyword is very poor, which would mean that I am using the tool the wrong way or it is simply not well implemented.
Someone please take a look at that.

Cheers,
Babzsak

**Comment by mihaiparvu** [comment]
Hello Babzsak,

There is indeed a problem with the documentation, the Send Keyword Event keyword calls Abbot, a dependency for SwingLibrary,  which provides its specific mappings for the keystrokes. 

Unfortunately, the VK_UNDERSCORE isn't mapped in Abbot's KeyStrokeMap, and as far as I know it is no longer developed (last release was in 2013).

As a workaround for your issue I suggest using the SHIFT_MASK modifier for the keyword.
E.g:  **Send Keyboard Event  VK_MINUS  SHIFT_MASK**
This should work on a US Locale keyboard setup, but I think can be modified for the other locales too.
I will update the keyword's documentation to be more accurate, in the next release.

Kind regards,
Mihai.
