### ISSUE TITLE
Close Window keyword terminates all robot tests

### ISSUE THREAD

**Issue by ehhc** [robotframework/SwingLibrary#99]
Hi guys,
I'm trying to test a Swing application and I’m using your library to control my Swing application.
In one test suite I have multiple test which all need to interact with the swing application. My problem arises because each test could potentially fail and therefore leave the application in a state with that the next test can’t work. Therefore I would like to open a new instance of the swing application for each test.
I have found out that I can use the “Test setup” method for this. Unfortunately having multiple instances of my Swing application can lead to problems. Therefore it is necessary to close each Swing application at the end of each test. I would like to do this using the “Test teardown” method.
The following code snipped shows my code
```
*** Settings ***

Test Setup  Starte Application
Test Teardown  Close Application

*** Test Cases ***
Test1
  Log  Test1

Test2
  Log  Test 2

*** Keywords ***
Starte Application
# Opens My Application

Close Application
  Close Window  My-Application

```

My problem now is the following: The “Close Window” keywords leads to a termination of my test suite. Test2 is never executed, no log-file is generated and my output.xml ends with a unexpected end of file (which isn’t a valid xml file anymore)
The end of my output.xml looks like the following:
```

<kw type="teardown" name="Close Application ">
<kw library="SwingLibrary" name="Close Window">
<doc>Closes a window.</doc>
<arguments>
<arg>My-Application</arg>
</arguments>


 
```
As you see the output.xml isn’t ended properly and the <kw>-Tag is never closed.
Do you have any ideas what I did wrong? Does the “Close Window”-Method should terminate the whole test suite? Do you have any ideas how to handle the problem?
I’m using Version 3.0.2 of the Robot framework and version 1.9.7 of the SwingLibrary

**Comment by mihaiparvu** [comment]
Hello ehhc,

The _Close Window_ keyword should NOT terminate the whole suite, just close the application. 
I've tried to reproduce this scenario using the test application, included in SwingLibrary, but everything works ok on my end. The first test closes the application succesfully and the second test opens it again.

You can try testing with:
`Start Application  org.robotframework.swing.testapp.TestApplication ` 
in your _Starte Application_ keyword and see if it works.

**Comment by ehhc** [comment]
Hi mihaiparvu,
thank you for your answer. You’re right. The keyword works correct. The problem was that we are using some ugly System.exit()-Code in our application that I wasn’t aware of.
Because I’m using the Java-Version of the Robot Framework closing our application leads to a termination of the JVM and that lead to the incorrect behaviour of the robot framework. 
So it’s neither your fault not the one of the robot framework. The problem is the System.exit in our code. 
Thanks again for your quick answer.
